# Generated by Django 3.2.7 on 2021-12-04 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Serv_Type', models.CharField(max_length=20)),
                ('Serv_Name', models.CharField(max_length=50)),
                ('Serv_Description', models.TextField()),
                ('Serv_Applied_Date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Serv_Req_Image', models.ImageField(upload_to='Serv_Comp_pics/')),
                ('Serv_Location', models.CharField(max_length=300)),
                ('Serv_Approval_Status', models.CharField(max_length=20)),
                ('Serv_Remarks', models.TextField()),
                ('Serv_Estimated_Completion_Date', models.DateTimeField()),
                ('Serv_Completion_Status', models.CharField(max_length=20)),
                ('Serv_Comp_Image', models.ImageField(upload_to='Serv_Comp_pics/')),
                ('Serv_Doc_Proof', models.FileField(upload_to='Files/')),
                ('Serv_Applied_By', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
