# Generated by Django 3.2.7 on 2021-12-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Serv_Estimated_Completion_Date',
            field=models.DateField(),
        ),
    ]
