# Generated by Django 3.2.7 on 2021-12-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0002_alter_services_serv_estimated_completion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cert_Type', models.CharField(max_length=50)),
                ('Cand_Name', models.CharField(max_length=50)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Mother_Name', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=300)),
                ('govt_id', models.CharField(max_length=30)),
                ('govt_proof_document', models.FileField(upload_to='Files/')),
                ('Birth_Date', models.DateField()),
                ('Birth_location', models.CharField(default=None, max_length=200)),
                ('Death_Date', models.DateField(default=None)),
                ('Death_location', models.CharField(default=None, max_length=200)),
                ('Cast', models.CharField(default=None, max_length=50)),
                ('Cast_Category', models.CharField(default=None, max_length=10)),
                ('Income_Value', models.CharField(default=None, max_length=20)),
                ('document_proof', models.FileField(default=None, upload_to='Files/')),
                ('Remarks', models.TextField()),
                ('Approval_Status', models.CharField(max_length=20)),
            ],
        ),
    ]
