# Generated by Django 3.2.7 on 2021-12-04 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0003_certificates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='Birth_location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
