# Generated by Django 3.2.7 on 2021-12-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0004_alter_certificates_birth_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='Cast',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Cast_Category',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Death_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Death_location',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='Income_Value',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='document_proof',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Files/'),
        ),
    ]
