# Generated by Django 3.2.7 on 2021-12-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0005_auto_20211204_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='Serv_City',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='services',
            name='Serv_Doc_Name',
            field=models.CharField(default='NULL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='Serv_State',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
