# Generated by Django 3.2.7 on 2021-12-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0006_auto_20211211_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Serv_Completion_Status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Doc_Name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Estimated_Completion_Date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Location',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Remarks',
            field=models.TextField(null=True),
        ),
    ]
