# Generated by Django 3.2.7 on 2021-12-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0007_auto_20211211_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Serv_Comp_Image',
            field=models.ImageField(default=None, upload_to='Serv_Comp_pics/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Estimated_Completion_Date',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Remarks',
            field=models.TextField(default=None, null=True),
        ),
    ]
