# Generated by Django 3.2.7 on 2021-12-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0008_auto_20211220_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Serv_Comp_Image',
            field=models.ImageField(blank=True, default=None, upload_to='Serv_Comp_pics/'),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Completion_Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Estimated_Completion_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='Serv_Remarks',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
