# Generated by Django 3.2.7 on 2021-12-21 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0010_auto_20211221_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='Serv_Location',
            field=models.CharField(default=None, max_length=300, null=True),
        ),
    ]
