# Generated by Django 4.0.4 on 2022-05-07 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0012_alter_services_serv_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='Completion_Status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='certificates',
            name='certificate',
            field=models.FileField(blank=True, default=None, null=True, upload_to='Certificates/'),
        ),
    ]
