# Generated by Django 4.0.4 on 2022-05-07 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0013_certificates_completion_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='Cert_Type',
            new_name='Cert_Name',
        ),
    ]
