# Generated by Django 4.0.4 on 2022-05-07 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Services', '0014_rename_cert_type_certificates_cert_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='Cert_Requested_By',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
