# Generated by Django 4.0.4 on 2022-05-07 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0015_certificates_cert_requested_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='phoneno',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
