# Generated by Django 4.0.4 on 2022-05-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0016_certificates_phoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='govt_id',
            new_name='doc_name',
        ),
        migrations.RemoveField(
            model_name='certificates',
            name='govt_proof_document',
        ),
    ]
