# Generated by Django 4.0.4 on 2022-05-07 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0017_rename_govt_id_certificates_doc_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='Cert_Applied_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
