# Generated by Django 4.0.4 on 2022-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Services', '0018_certificates_cert_applied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='Cert_Estimated_Completion_Date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
